# Generated by Django 3.0.3 on 2020-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(default=' ', max_length=15)),
                ('field_status', models.BooleanField(default=False, help_text='container state')),
                ('field_user', models.CharField(default=' ', max_length=10)),
            ],
        ),
    ]
